NAME = libft.a

SRCS = srcs/ft_putchar.c srcs/ft_putstr.c srcs/ft_strcmp.c srcs/ft_strlen.c srcs/ft_swap.c

OBJS = ft_putchar.o ft_putstr.o ft_strcmp.o ft_strlen.o ft_swap.o

CC = gcc
CFLAGS = -Wall -Wextra -Werror
INCLUDES = -I includes

all: $(NAME)

$(NAME): $(OBJS)
	ar rcs $(NAME) $(OBJS)

ft_putchar.o: srcs/ft_putchar.c
	$(CC) $(CFLAGS) $(INCLUDES) -c srcs/ft_putchar.c -o ft_putchar.o

ft_putstr.o: srcs/ft_putstr.c
	$(CC) $(CFLAGS) $(INCLUDES) -c srcs/ft_putstr.c -o ft_putstr.o

ft_strcmp.o: srcs/ft_strcmp.c
	$(CC) $(CFLAGS) $(INCLUDES) -c srcs/ft_strcmp.c -o ft_strcmp.o

ft_strlen.o: srcs/ft_strlen.c
	$(CC) $(CFLAGS) $(INCLUDES) -c srcs/ft_strlen.c -o ft_strlen.o

ft_swap.o: srcs/ft_swap.c
	$(CC) $(CFLAGS) $(INCLUDES) -c srcs/ft_swap.c -o ft_swap.o

clean:
	rm -f $(OBJS)

fclean: clean
	rm -f $(NAME)

re: fclean all